### ISSUE TITLE
Request for the currated tables

### ISSUE THREAD

**Issue by yihengpan** [tystan/fuzzyfaers#1]
Hi Ty,
Thanks for your great work! It seems I cannot see the currate tables through the link. It appears my Dropbox homepage. Could you please check and provide the access? Thanks in advanced!

**Comment by tystan** [comment]
Hi @yihengpan. My apologies, I did not see a notification of your request. I plan to sort this out this week! Thanks, Ty

**Comment by tystan** [comment]
Hi @yihengpan. The csvs are now available for download, see: https://github.com/tystan/fuzzyfaers/blob/master/postgres/csvs-url.txt (and the README.md is updated too)
